name: "Trivy PR Commenter"
description: "Runs Trivy and adds comments to the PR where checks have failed"

inputs:
  github_token:
    description: "GitHub token"
    required: true
  working_directory:
    required: false
    description: |
      Directory to run the action on, from the repo root.
      Default is . (root of the repository)
    default: "."
  trivy_version:
    required: false
    description: "The version of Trivy to use, defaults to latest"
    default: latest
  trivy_report_path:
    required: true
    description: "Path to the Trivy scan report JSON file"
  soft_fail_commenter:
    required: false
    description: "If set to `true`, will silently comment without breaking the build"
outputs:
  trivy_return_code:
    description: "Trivy command return code"
runs:
  using: "docker"
  image: "Dockerfile"
branding:
  icon: "git-pull-request"
  color: "purple"
